CREATE DATABASE NotesDb;
GO

USE NotesDb;
GO

CREATE TABLE Notes
(
    Id INT IDENTITY PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Content NVARCHAR(MAX),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL,
    UserId INT NOT NULL
);
